<a href="https://colab.research.google.com/github/Vengadesh58/Pytorch/blob/main/pytorch_fundamentals00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

In [2]:
!nvidia-smi

Mon Aug 26 05:25:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
 ## Introductions to tensor

 # Creating tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector[0]

tensor(7)

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0].shape

torch.Size([2])

In [16]:
#Tensor
TENSOR = torch.tensor([
    [[1,2,3],
      [3,6,9],
      [2,4,3]],
    [[1,2,3],
     [2,3,4],
      [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 3]],

        [[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

In [19]:
## Random tensors
random_tensor = torch.rand(3,3,3,)
random_tensor


tensor([[[0.0182, 0.9081, 0.5460],
         [0.5081, 0.5683, 0.6123],
         [0.9250, 0.1152, 0.1725]],

        [[0.7950, 0.3039, 0.9228],
         [0.1605, 0.8911, 0.4143],
         [0.5087, 0.5956, 0.9112]],

        [[0.2381, 0.6732, 0.5810],
         [0.9128, 0.6156, 0.3138],
         [0.9415, 0.4902, 0.2640]]])

In [20]:
random_tensor.ndim

3

In [21]:
#create a random tensor similar to the image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels(RGB)
random_image_size_tensor.shape,random_image_size_tensor.ndim



(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(size=(3,4))

tensor([[0.6866, 0.2421, 0.6063, 0.3092],
        [0.6196, 0.5295, 0.0739, 0.2900],
        [0.8479, 0.9362, 0.2993, 0.9805]])

### Zeros and ones

In [23]:
### Zeros and ones

zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [25]:
#create tensor of ones

ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Range of tensors

In [27]:
#creating a range of tensors

torch.arange(0,10)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#creating tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,#dtype float32, float16,float64
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
### Getting information from tensors

some_tensor = torch.rand(3,4)
some_tensor

some_tensor.dtype

torch.float32

In [34]:
some_tensor.shape

torch.Size([3, 4])

In [35]:
some_tensor.device

device(type='cpu')

## Tensor Opperation

In [36]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [38]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [39]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### PyTorch tensors & Numpy

In [40]:
#numpy arraty to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [41]:
#torch tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [42]:
#random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [43]:
!nvidia-smi

Mon Aug 26 05:25:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [44]:
## 2. check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

In [45]:
#Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [46]:
#count the nuber of deivces

torch.cuda.device_count()

1

In [49]:
## putting tensors and mnodels on the GPU

tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [50]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')