<a href="https://colab.research.google.com/github/Vengadesh58/Pytorch/blob/main/pytorch_fundamentals00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
 ## Introductions to tensor

 # Creating tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector[0]

tensor(7)

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0].shape

torch.Size([2])

In [16]:
#Tensor
TENSOR = torch.tensor([
    [[1,2,3],
      [3,6,9],
      [2,4,3]],
    [[1,2,3],
     [2,3,4],
      [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 3]],

        [[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

In [27]:
## Random tensors
random_tensor = torch.rand(3,4,4,)
random_tensor


tensor([[[0.0201, 0.1383, 0.0749, 0.3011],
         [0.4971, 0.7760, 0.1868, 0.1419],
         [0.1098, 0.4569, 0.1488, 0.9692],
         [0.8484, 0.9372, 0.1018, 0.5899]],

        [[0.3210, 0.5741, 0.2589, 0.6474],
         [0.6526, 0.1603, 0.1608, 0.2714],
         [0.6339, 0.9575, 0.9804, 0.4026],
         [0.5336, 0.9928, 0.1033, 0.7231]],

        [[0.9791, 0.9642, 0.2671, 0.6339],
         [0.5125, 0.0180, 0.8673, 0.1306],
         [0.2354, 0.3190, 0.0615, 0.5257],
         [0.8624, 0.8459, 0.0262, 0.1376]]])

In [20]:
random_tensor.ndim

3

In [30]:
#create a random tensor similar to the image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels(RGB)
random_image_size_tensor.shape,random_image_size_tensor.ndim



(torch.Size([224, 224, 3]), 3)